### ISSUE TITLE
footer margin

### ISSUE THREAD

**Issue by Lesley55** [Lesley55/webdesign#12]
in de div van de footer staat css style margin-bottom: 0; het is niet de bedoeling dat dit in html staat, maar als ik het verplaats naar css komt er een 32 px margin onderaan, en werkt dit niet meer

**Comment by DS946256** [comment]
Heb het werkend gekregen. Weet niet of het wel is zo als je het wil. Heb er wel voor een extra CSS regels aan het eind toegevoegd zodat de class binnen de footer bereikt kon worden. Het staat op de master branch
